<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Bank_transfer</name>
   <tag></tag>
   <elementGuidId>b1550a12-2fef-4123-bd7d-01750a7b853e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/section/div[7]/div[3]/div/ul/li[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/section/div[7]/div[3]/div/ul/li[6]</value>
   </webElementProperties>
</WebElementEntity>
