<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>bayar_di_outlet</name>
   <tag></tag>
   <elementGuidId>4ac7cccd-11fb-4d90-92fc-280905f5d200</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/section/div[7]/div[3]/div/ul/li[11]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/section/div[7]/div[3]/div/ul/li[11]</value>
   </webElementProperties>
</WebElementEntity>
