<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>bca_klikpay</name>
   <tag></tag>
   <elementGuidId>1c7c4e9d-41e8-4705-b2cd-dedf0085089d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/section/div[7]/div[3]/div/ul/li[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/section/div[7]/div[3]/div/ul/li[4]</value>
   </webElementProperties>
</WebElementEntity>
