<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Klik_bca</name>
   <tag></tag>
   <elementGuidId>ef1f44e6-39c9-4c67-8647-eb2bc5bc0044</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/section/div[7]/div[3]/div/ul/li[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/section/div[7]/div[3]/div/ul/li[2]</value>
   </webElementProperties>
</WebElementEntity>
