<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_BNI_Virtual_Account</name>
   <tag></tag>
   <elementGuidId>34def65c-a8cc-4721-9ff6-ac8f524bd1ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;tab-2&quot;]/ul/li[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;tab-2&quot;]/ul/li[2]</value>
   </webElementProperties>
</WebElementEntity>
