<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_BRI_kartu_kredit</name>
   <tag></tag>
   <elementGuidId>12662828-569c-4964-b300-82f0ff4655c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;tab-3&quot;]/ul/li[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;tab-3&quot;]/ul/li[3]</value>
   </webElementProperties>
</WebElementEntity>
