<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_mandiri_e-cash</name>
   <tag></tag>
   <elementGuidId>d5cb7143-1417-4eba-bdd5-36c25a13f17f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;tab-1&quot;]/ul/li[3]/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;tab-1&quot;]/ul/li[3]/div/label</value>
   </webElementProperties>
</WebElementEntity>
