<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_BRI_kartu_kredit_cicilan</name>
   <tag></tag>
   <elementGuidId>90d2270f-250e-457d-9725-a335e1339d82</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;tab-3&quot;]/ul/li[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;tab-3&quot;]/ul/li[4]</value>
   </webElementProperties>
</WebElementEntity>
