<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_BNI_SMS_payment</name>
   <tag></tag>
   <elementGuidId>aa9c42c2-b35d-4df8-86c0-572281c91a01</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;tab-2&quot;]/ul/li[5]/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;tab-2&quot;]/ul/li[5]/div/label</value>
   </webElementProperties>
</WebElementEntity>
